### ISSUE TITLE
Is focusing on `describe` blocks supported when I click a line?

### ISSUE THREAD

**Issue by Wizek** [taras42/karma-jasmine-html-reporter#2]
What I mean is detailed here:
http://stackoverflow.com/questions/28819177/when-using-karmajasmine-is-it-possible-to-select-describe-blocks-to-run-with
Can this plugin work the same way as described there?

**Comment by taras42** [comment]
Hello, you can click on describe that you want to run (in browser). But
still, I haven't found a way to do this in console. (API that you mentioned
in a link above). I will add some screen shots.

понеділок, 2 березня 2015 р. користувач Wizek notifications@github.com
написав:

**Comment by Wizek** [comment]
Thanks!

**Comment by Wizek** [comment]
I've just tried it out and focusing-by-clicking works indeed! :) Nice!
