### ISSUE TITLE
Does this work together with gulp-karma?

### ISSUE THREAD

**Issue by adamreisnz** [taras42/karma-jasmine-html-reporter#7]
I've followed the instructions of this package, but no output is being generated.
Do you know if this reporter works together with gulp-karma?

**Comment by taras42** [comment]
Hi,

This reporter does not generate any file as output. Instead you should run karma with singleRun options to be false, and then open htts://localhost:9876/debug.html and here you should see tests results.

9876 is default port. 

I have not tried it with gulp-karma. But probably it should work.

Sorry for not responding quite long time, did not noticed issue.

**Comment by adamreisnz** [comment]
Ok thanks, I'll look into it.
