### ISSUE TITLE
No debug.html file created 

### ISSUE THREAD

**Issue by merlosy** [taras42/karma-jasmine-html-reporter#8]
Hi,
My tests are fine in the console, and no file is generated by the reporter. It's like nothing happened..
Even though I added the conf to my `karma.conf.js`.
I'm using Jasmine 2.0.0.
In my package.json :

```
    "karma": "~0.13",
    "karma-coverage": "^0.5.0",
    "karma-jasmine": "~0.2.0",
    "karma-jasmine-html-reporter": "~0.1",
    "karma-phantomjs-launcher": "~0.2.0",
```

It's all the latest dependencies so far..

Please any suggestion?

**Comment by taras42** [comment]
Hi,
Reporter does not generate any files. You should run karma, then open your browser at http://localhost:9876/debug.html. Here you should see tests being run.

**Comment by taras42** [comment]
Just be sure to run karma with singleRun option to be false. Otherwise, it will run tests and then shutdown.

**Comment by merlosy** [comment]
It's working! Found it on http://localhost:8080/debug.html
Maybe you could update your `readme.md` with the `singleRun: false` config.

Thanks!
